name: Build Debian Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deb:
    uses: charlieh0tel/deb-workflows/.github/workflows/rust-build-deb.yml@main
    with:
      build-deps: "llvm-dev libclang-dev libasound2-dev libespeak-ng-dev"
    secrets: inherit
